const VENEZUELA_MUNICIPALITIES = [
  { "municipio": "Alto Orinoco", "estado": "Amazonas", "capital": "La Esmeralda", "latitud": 3.17278, "longitud": -65.5475 },
  { "municipio": "Atabapo", "estado": "Amazonas", "capital": "San Fernando de Atabapo", "latitud": 4.04472, "longitud": -67.695 },
  { "municipio": "Atures", "estado": "Amazonas", "capital": "Puerto Ayacucho", "latitud": 5.66389, "longitud": -67.6236 },
  { "municipio": "Autana", "estado": "Amazonas", "capital": "Isla Ratón", "latitud": 4.83333, "longitud": -67.8 },
  { "municipio": "Manapiare", "estado": "Amazonas", "capital": "San Juan de Manapiare", "latitud": 5.31667, "longitud": -66.05 },
  { "municipio": "Maroa", "estado": "Amazonas", "capital": "Maroa", "latitud": 2.71667, "longitud": -67.55 },
  { "municipio": "Río Negro", "estado": "Amazonas", "capital": "San Carlos de Río Negro", "latitud": 1.91667, "longitud": -67.0667 },
  { "municipio": "Anaco", "estado": "Anzoátegui", "capital": "Anaco", "latitud": 9.43333, "longitud": -64.4667 },
  { "municipio": "Aragua", "estado": "Anzoátegui", "capital": "Aragua de Barcelona", "latitud": 9.45, "longitud": -64.8333 },
  { "municipio": "Bolívar", "estado": "Anzoátegui", "capital": "Barcelona", "latitud": 10.1333, "longitud": -64.6833 },
  { "municipio": "Bruzual", "estado": "Anzoátegui", "capital": "Clarines", "latitud": 9.93333, "longitud": -65.1667 },
  { "municipio": "Cajigal", "estado": "Anzoátegui", "capital": "Onoto", "latitud": 9.56667, "longitud": -65.15 },
  { "municipio": "Carvajal", "estado": "Anzoátegui", "capital": "Valle de Guanape", "latitud": 9.95, "longitud": -65.5833 },
  { "municipio": "Diego Bautista Urbaneja", "estado": "Anzoátegui", "capital": "Lechería", "latitud": 10.1833, "longitud": -64.6833 },
  { "municipio": "Freites", "estado": "Anzoátegui", "capital": "Cantaura", "latitud": 9.3, "longitud": -64.35 },
  { "municipio": "Guanipa", "estado": "Anzoátegui", "capital": "San José de Guanipa", "latitud": 8.88333, "longitud": -64.1667 },
  { "municipio": "Guanta", "estado": "Anzoátegui", "capital": "Guanta", "latitud": 10.2333, "longitud": -64.5833 },
  { "municipio": "Independencia", "estado": "Anzoátegui", "capital": "Soledad", "latitud": 8.13333, "longitud": -63.55 },
  { "municipio": "Libertad", "estado": "Anzoátegui", "capital": "San Mateo", "latitud": 9.8, "longitud": -64.45 },
  { "municipio": "McGregor", "estado": "Anzoátegui", "capital": "El Chaparro", "latitud": 9.33333, "longitud": -64.9167 },
  { "municipio": "Miranda", "estado": "Anzoátegui", "capital": "Pariaguán", "latitud": 8.8, "longitud": -64.7 },
  { "municipio": "Monagas", "estado": "Anzoátegui", "capital": "Mapire", "latitud": 7.73333, "longitud": -64.7167 },
  { "municipio": "Peñalver", "estado": "Anzoátegui", "capital": "Puerto Píritu", "latitud": 10.0667, "longitud": -65.0333 },
  { "municipio": "Píritu", "estado": "Anzoátegui", "capital": "Píritu", "latitud": 10.05, "longitud": -65.0333 },
  { "municipio": "San Juan de Capistrano", "estado": "Anzoátegui", "capital": "Boca de Uchire", "latitud": 10.0333, "longitud": -65.3 },
  { "municipio": "Santa Ana", "estado": "Anzoátegui", "capital": "Santa Ana", "latitud": 9.36667, "longitud": -64.5667 },
  { "municipio": "Simón Rodríguez", "estado": "Anzoátegui", "capital": "El Tigre", "latitud": 8.88333, "longitud": -64.2667 },
  { "municipio": "Sotillo", "estado": "Anzoátegui", "capital": "Puerto La Cruz", "latitud": 10.2167, "longitud": -64.6167 },
  { "municipio": "Achaguas", "estado": "Apure", "capital": "Achaguas", "latitud": 7.78333, "longitud": -68.2167 },
  { "municipio": "Biruaca", "estado": "Apure", "capital": "Biruaca", "latitud": 7.85, "longitud": -67.5 },
  { "municipio": "Muñoz", "estado": "Apure", "capital": "Bruzual", "latitud": 8.05, "longitud": -69.3333 },
  { "municipio": "Páez", "estado": "Apure", "capital": "Guasdualito", "latitud": 7.25, "longitud": -70.7333 },
  { "municipio": "Pedro Camejo", "estado": "Apure", "capital": "San Juan de Payara", "latitud": 7.61667, "longitud": -67.6 },
  { "municipio": "Rómulo Gallegos", "estado": "Apure", "capital": "Elorza", "latitud": 7.06667, "longitud": -69.5 },
  { "municipio": "San Fernando", "estado": "Apure", "capital": "San Fernando de Apure", "latitud": 7.88333, "longitud": -67.4667 },
  { "municipio": "Bolívar", "estado": "Aragua", "capital": "San Mateo", "latitud": 10.2, "longitud": -67.45 },
  { "municipio": "Camatagua", "estado": "Aragua", "capital": "Camatagua", "latitud": 9.85, "longitud": -67.2833 },
  { "municipio": "Girardot", "estado": "Aragua", "capital": "Maracay", "latitud": 10.2353, "longitud": -67.5911 },
  { "municipio": "José Ángel Lamas", "estado": "Aragua", "capital": "Santa Cruz", "latitud": 10.2, "longitud": -67.5333 },
  { "municipio": "José Félix Ribas", "estado": "Aragua", "capital": "La Victoria", "latitud": 10.2333, "longitud": -67.3333 },
  { "municipio": "José Rafael Revenga", "estado": "Aragua", "capital": "El Consejo", "latitud": 10.25, "longitud": -67.3 },
  { "municipio": "Libertador", "estado": "Aragua", "capital": "Palo Negro", "latitud": 10.1667, "longitud": -67.6 },
  { "municipio": "Mario Briceño Iragorry", "estado": "Aragua", "capital": "El Limón", "latitud": 10.3, "longitud": -67.6333 },
  { "municipio": "Ocumare de la Costa de Oro", "estado": "Aragua", "capital": "Ocumare de la Costa", "latitud": 10.4667, "longitud": -67.7667 },
  { "municipio": "San Casimiro", "estado": "Aragua", "capital": "San Casimiro", "latitud": 10, "longitud": -67.0167 },
  { "municipio": "San Sebastián", "estado": "Aragua", "capital": "San Sebastián de los Reyes", "latitud": 9.85, "longitud": -67.1833 },
  { "municipio": "Santiago Mariño", "estado": "Aragua", "capital": "Turmero", "latitud": 10.2333, "longitud": -67.4833 },
  { "municipio": "Santos Michelena", "estado": "Aragua", "capital": "Las Tejerías", "latitud": 10.25, "longitud": -67.1667 },
  { "municipio": "Sucre", "estado": "Aragua", "capital": "Cagua", "latitud": 10.1833, "longitud": -67.45 },
  { "municipio": "Tovar", "estado": "Aragua", "capital": "Colonia Tovar", "latitud": 10.4167, "longitud": -67.2833 },
  { "municipio": "Urdaneta", "estado": "Aragua", "capital": "Barbacoas", "latitud": 9.6, "longitud": -67.2 },
  { "municipio": "Zamora", "estado": "Aragua", "capital": "Villa de Cura", "latitud": 10.05, "longitud": -67.5 },
  { "municipio": "Alberto Arvelo Torrealba", "estado": "Barinas", "capital": "Sabaneta", "latitud": 8.76667, "longitud": -69.95 },
  { "municipio": "Andrés Eloy Blanco", "estado": "Barinas", "capital": "El Cantón", "latitud": 7.6, "longitud": -71.5 },
  { "municipio": "Antonio José de Sucre", "estado": "Barinas", "capital": "Socopó", "latitud": 8.23333, "longitud": -70.8167 },
  { "municipio": "Arismendi", "estado": "Barinas", "capital": "Arismendi", "latitud": 8.5, "longitud": -69.3 },
  { "municipio": "Barinas", "estado": "Barinas", "capital": "Barinas", "latitud": 8.63333, "longitud": -70.2 },
  { "municipio": "Bolívar", "estado": "Barinas", "capital": "Barinitas", "latitud": 8.76667, "longitud": -70.4167 },
  { "municipio": "Cruz Paredes", "estado": "Barinas", "capital": "Barrancas", "latitud": 8.75, "longitud": -70.1 },
  { "municipio": "Ezequiel Zamora", "estado": "Barinas", "capital": "Santa Bárbara", "latitud": 7.81667, "longitud": -71.1667 },
  { "municipio": "Obispos", "estado": "Barinas", "capital": "Obispos", "latitud": 8.7, "longitud": -70.25 },
  { "municipio": "Pedraza", "estado": "Barinas", "capital": "Ciudad Bolivia", "latitud": 8.35, "longitud": -70.6667 },
  { "municipio": "Rojas", "estado": "Barinas", "capital": "Libertad", "latitud": 8.9, "longitud": -69.6 },
  { "municipio": "Sosa", "estado": "Barinas", "capital": "Ciudad de Nutrias", "latitud": 8.3, "longitud": -69.9 },
  { "municipio": "Caroní", "estado": "Bolívar", "capital": "Ciudad Guayana", "latitud": 8.37528, "longitud": -62.6208 },
  { "municipio": "Cedeño", "estado": "Bolívar", "capital": "Caicara del Orinoco", "latitud": 7.63333, "longitud": -66.1667 },
  { "municipio": "El Callao", "estado": "Bolívar", "capital": "El Callao", "latitud": 7.35, "longitud": -61.8667 },
  { "municipio": "Gran Sabana", "estado": "Bolívar", "capital": "Santa Elena de Uairén", "latitud": 4.6, "longitud": -61.1167 },
  { "municipio": "Heres", "estado": "Bolívar", "capital": "Ciudad Bolívar", "latitud": 8.11667, "longitud": -63.55 },
  { "municipio": "Piar", "estado": "Bolívar", "capital": "Upata", "latitud": 8.01667, "longitud": -62.4 },
  { "municipio": "Raúl Leoni", "estado": "Bolívar", "capital": "Ciudad Piar", "latitud": 7.5, "longitud": -63.1 },
  { "municipio": "Roscio", "estado": "Bolívar", "capital": "Guasipati", "latitud": 7.46667, "longitud": -61.9 },
  { "municipio": "Sifontes", "estado": "Bolívar", "capital": "Tumeremo", "latitud": 7.25, "longitud": -61.4167 },
  { "municipio": "Sucre", "estado": "Bolívar", "capital": "Maripa", "latitud": 7.4, "longitud": -65.1 },
  { "municipio": "Padre Pedro Chien", "estado": "Bolívar", "capital": "El Palmar", "latitud": 7.7, "longitud": -61.8 },
  { "municipio": "Bejuma", "estado": "Carabobo", "capital": "Bejuma", "latitud": 10.1667, "longitud": -68.2667 },
  { "municipio": "Carlos Arvelo", "estado": "Carabobo", "capital": "Güigüe", "latitud": 10.0833, "longitud": -67.7833 },
  { "municipio": "Diego Ibarra", "estado": "Carabobo", "capital": "Mariara", "latitud": 10.3, "longitud": -67.7167 },
  { "municipio": "Guacara", "estado": "Carabobo", "capital": "Guacara", "latitud": 10.2333, "longitud": -67.8833 },
  { "municipio": "Juan José Mora", "estado": "Carabobo", "capital": "Morón", "latitud": 10.4833, "longitud": -68.2 },
  { "municipio": "Libertador", "estado": "Carabobo", "capital": "Tocuyito", "latitud": 10.1167, "longitud": -68.0833 },
  { "municipio": "Los Guayos", "estado": "Carabobo", "capital": "Los Guayos", "latitud": 10.1833, "longitud": -67.9333 },
  { "municipio": "Miranda", "estado": "Carabobo", "capital": "Miranda", "latitud": 10.1, "longitud": -68.1833 },
  { "municipio": "Montalbán", "estado": "Carabobo", "capital": "Montalbán", "latitud": 10.2167, "longitud": -68.3167 },
  { "municipio": "Naguanagua", "estado": "Carabobo", "capital": "Naguanagua", "latitud": 10.25, "longitud": -68 },
  { "municipio": "Puerto Cabello", "estado": "Carabobo", "capital": "Puerto Cabello", "latitud": 10.4667, "longitud": -68.0167 },
  { "municipio": "San Diego", "estado": "Carabobo", "capital": "San Diego", "latitud": 10.2333, "longitud": -67.95 },
  { "municipio": "San Joaquín", "estado": "Carabobo", "capital": "San Joaquín", "latitud": 10.2667, "longitud": -67.8 },
  { "municipio": "Valencia", "estado": "Carabobo", "capital": "Valencia", "latitud": 10.1621, "longitud": -68.0078 },
  { "municipio": "Anzoátegui", "estado": "Cojedes", "capital": "Cojedes", "latitud": 9.6, "longitud": -68.9 },
  { "municipio": "Falcón", "estado": "Cojedes", "capital": "Tinaquillo", "latitud": 9.91667, "longitud": -68.3 },
  { "municipio": "Girardot", "estado": "Cojedes", "capital": "El Baúl", "latitud": 8.96667, "longitud": -68.3 },
  { "municipio": "Lima Blanco", "estado": "Cojedes", "capital": "Macapo", "latitud": 9.8, "longitud": -68.5 },
  { "municipio": "Pao de San Juan Bautista", "estado": "Cojedes", "capital": "El Pao", "latitud": 9.66667, "longitud": -68.1167 },
  { "municipio": "Ricaurte", "estado": "Cojedes", "capital": "Libertad", "latitud": 9.6, "longitud": -68.7 },
  { "municipio": "Rómulo Gallegos", "estado": "Cojedes", "capital": "Las Vegas", "latitud": 9.7, "longitud": -68.6 },
  { "municipio": "San Carlos", "estado": "Cojedes", "capital": "San Carlos", "latitud": 9.65, "longitud": -68.5833 },
  { "municipio": "Tinaco", "estado": "Cojedes", "capital": "Tinaco", "latitud": 9.7, "longitud": -68.4333 },
  { "municipio": "Antonio Díaz", "estado": "Delta Amacuro", "capital": "Curiapo", "latitud": 8.56667, "longitud": -60.9833 },
  { "municipio": "Casacoima", "estado": "Delta Amacuro", "capital": "Sierra Imataca", "latitud": 8.45, "longitud": -61.5 },
  { "municipio": "Pedernales", "estado": "Delta Amacuro", "capital": "Pedernales", "latitud": 9.96667, "longitud": -62.2333 },
  { "municipio": "Tucupita", "estado": "Delta Amacuro", "capital": "Tucupita", "latitud": 9.05, "longitud": -62.05 },
  { "municipio": "Libertador", "estado": "Distrito Capital", "capital": "Caracas", "latitud": 10.488, "longitud": -66.8792 },
  { "municipio": "Acosta", "estado": "Falcón", "capital": "San Juan de los Cayos", "latitud": 11.2, "longitud": -68.3 },
  { "municipio": "Bolívar", "estado": "Falcón", "capital": "San Luis", "latitud": 11.1, "longitud": -69.6 },
  { "municipio": "Buchivacoa", "estado": "Falcón", "capital": "Capatárida", "latitud": 11.2, "longitud": -70.6 },
  { "municipio": "Cacique Manaure", "estado": "Falcón", "capital": "Yaracal", "latitud": 11.1, "longitud": -68.8 },
  { "municipio": "Carirubana", "estado": "Falcón", "capital": "Punto Fijo", "latitud": 11.7167, "longitud": -70.1833 },
  { "municipio": "Colina", "estado": "Falcón", "capital": "La Vela de Coro", "latitud": 11.4667, "longitud": -69.5667 },
  { "municipio": "Dabajuro", "estado": "Falcón", "capital": "Dabajuro", "latitud": 10.6333, "longitud": -70.9667 },
  { "municipio": "Democracia", "estado": "Falcón", "capital": "Pedregal", "latitud": 11, "longitud": -70.1 },
  { "municipio": "Falcón", "estado": "Falcón", "capital": "Pueblo Nuevo", "latitud": 11.8, "longitud": -69.9 },
  { "municipio": "Federación", "estado": "Falcón", "capital": "Churuguara", "latitud": 10.8167, "longitud": -69.6167 },
  { "municipio": "Jacura", "estado": "Falcón", "capital": "Jacura", "latitud": 11, "longitud": -68.8 },
  { "municipio": "Los Taques", "estado": "Falcón", "capital": "Santa Cruz de Los Taques", "latitud": 11.8, "longitud": -70.2 },
  { "municipio": "Mauroa", "estado": "Falcón", "capital": "Mene de Mauroa", "latitud": 10.5, "longitud": -70.3 },
  { "municipio": "Miranda", "estado": "Falcón", "capital": "Coro", "latitud": 11.395, "longitud": -69.6817 },
  { "municipio": "Monseñor Iturriza", "estado": "Falcón", "capital": "Chichiriviche", "latitud": 10.9, "longitud": -68.2 },
  { "municipio": "Palmasola", "estado": "Falcón", "capital": "Palmasola", "latitud": 10.7, "longitud": -68.5 },
  { "municipio": "Petit", "estado": "Falcón", "capital": "Cabure", "latitud": 11.1, "longitud": -69.7 },
  { "municipio": "Píritu", "estado": "Falcón", "capital": "Píritu", "latitud": 11.1, "longitud": -69.3 },
  { "municipio": "San Francisco", "estado": "Falcón", "capital": "Mirimire", "latitud": 11.1667, "longitud": -68.6333 },
  { "municipio": "Silva", "estado": "Falcón", "capital": "Tucacas", "latitud": 10.8, "longitud": -68.3 },
  { "municipio": "Sucre", "estado": "Falcón", "capital": "La Cruz de Taratara", "latitud": 11.2, "longitud": -69.5 },
  { "municipio": "Tocópero", "estado": "Falcón", "capital": "Tocópero", "latitud": 11.4, "longitud": -69.9 },
  { "municipio": "Unión", "estado": "Falcón", "capital": "Santa Cruz de Bucaral", "latitud": 10.7, "longitud": -69.4 },
  { "municipio": "Urumaco", "estado": "Falcón", "capital": "Urumaco", "latitud": 11.2, "longitud": -70.2 },
  { "municipio": "Zamora", "estado": "Falcón", "capital": "Puerto Cumarebo", "latitud": 11.4, "longitud": -69.3 },
  { "municipio": "Camaguán", "estado": "Guárico", "capital": "Camaguán", "latitud": 8.1, "longitud": -67.6 },
  { "municipio": "Chaguaramas", "estado": "Guárico", "capital": "Chaguaramas", "latitud": 9.4, "longitud": -66.3 },
  { "municipio": "El Socorro", "estado": "Guárico", "capital": "El Socorro", "latitud": 9.1, "longitud": -65.7 },
  { "municipio": "Infante", "estado": "Guárico", "capital": "Valle de la Pascua", "latitud": 9.2, "longitud": -66 },
  { "municipio": "Las Mercedes", "estado": "Guárico", "capital": "Las Mercedes", "latitud": 9, "longitud": -66.5 },
  { "municipio": "Mellado", "estado": "Guárico", "capital": "El Sombrero", "latitud": 9.4, "longitud": -67 },
  { "municipio": "Miranda", "estado": "Guárico", "capital": "Calabozo", "latitud": 8.91667, "longitud": -67.4167 },
  { "municipio": "Monagas", "estado": "Guárico", "capital": "Altagracia de Orituco", "latitud": 9.85, "longitud": -66.3833 },
  { "municipio": "Ortiz", "estado": "Guárico", "capital": "Ortiz", "latitud": 9.6, "longitud": -67.3 },
  { "municipio": "Roscio", "estado": "Guárico", "capital": "San Juan de los Morros", "latitud": 9.9, "longitud": -67.35 },
  { "municipio": "Ribas", "estado": "Guárico", "capital": "Tucupido", "latitud": 9.3, "longitud": -65.8 },
  { "municipio": "San Gerónimo de Guayabal", "estado": "Guárico", "capital": "Guayabal", "latitud": 8.3, "longitud": -67.6 },
  { "municipio": "San José de Guaribe", "estado": "Guárico", "capital": "San José de Guaribe", "latitud": 9.6, "longitud": -65.9 },
  { "municipio": "Santa María de Ipire", "estado": "Guárico", "capital": "Santa María de Ipire", "latitud": 8.8, "longitud": -65.3 },
  { "municipio": "Zaraza", "estado": "Guárico", "capital": "Zaraza", "latitud": 9.35, "longitud": -65.3167 },
  { "municipio": "Andrés Eloy Blanco", "estado": "Lara", "capital": "Sanare", "latitud": 9.7, "longitud": -69.6 },
  { "municipio": "Crespo", "estado": "Lara", "capital": "Duaca", "latitud": 10.2833, "longitud": -69.1667 },
  { "municipio": "Iribarren", "estado": "Lara", "capital": "Barquisimeto", "latitud": 10.0647, "longitud": -69.3103 },
  { "municipio": "Jiménez", "estado": "Lara", "capital": "Quíbor", "latitud": 9.91667, "longitud": -69.6167 },
  { "municipio": "Morán", "estado": "Lara", "capital": "El Tocuyo", "latitud": 9.78333, "longitud": -69.8 },
  { "municipio": "Palavecino", "estado": "Lara", "capital": "Cabudare", "latitud": 10.0333, "longitud": -69.25 },
  { "municipio": "Simón Planas", "estado": "Lara", "capital": "Sarare", "latitud": 9.8, "longitud": -69.1 },
  { "municipio": "Torres", "estado": "Lara", "capital": "Carora", "latitud": 10.1667, "longitud": -70.0833 },
  { "municipio": "Urdaneta", "estado": "Lara", "capital": "Siquisique", "latitud": 10.5, "longitud": -69.4 },
  { "municipio": "Alberto Adriani", "estado": "Mérida", "capital": "El Vigía", "latitud": 8.61667, "longitud": -71.65 },
  { "municipio": "Andrés Bello", "estado": "Mérida", "capital": "La Azulita", "latitud": 8.7, "longitud": -71.4 },
  { "municipio": "Antonio Pinto Salinas", "estado": "Mérida", "capital": "Santa Cruz de Mora", "latitud": 8.4, "longitud": -71.6 },
  { "municipio": "Aricagua", "estado": "Mérida", "capital": "Aricagua", "latitud": 8.3, "longitud": -71.1 },
  { "municipio": "Arzobispo Chacón", "estado": "Mérida", "capital": "Canaguá", "latitud": 8.2, "longitud": -71.3 },
  { "municipio": "Campo Elías", "estado": "Mérida", "capital": "Ejido", "latitud": 8.55, "longitud": -71.2333 },
  { "municipio": "Caracciolo Parra Olmedo", "estado": "Mérida", "capital": "Tucaní", "latitud": 9, "longitud": -71.2 },
  { "municipio": "Cardenal Quintero", "estado": "Mérida", "capital": "Santo Domingo", "latitud": 8.8, "longitud": -70.7 },
  { "municipio": "Guaraque", "estado": "Mérida", "capital": "Guaraque", "latitud": 8.3, "longitud": -71.5 },
  { "municipio": "Julio César Salas", "estado": "Mérida", "capital": "Arapuey", "latitud": 9.1, "longitud": -71 },
  { "municipio": "Justo Briceño", "estado": "Mérida", "capital": "Torondoy", "latitud": 8.9, "longitud": -71.1 },
  { "municipio": "Libertador", "estado": "Mérida", "capital": "Mérida", "latitud": 8.58333, "longitud": -71.1333 },
  { "municipio": "Miranda", "estado": "Mérida", "capital": "Timotes", "latitud": 8.9, "longitud": -70.7 },
  { "municipio": "Obispo Ramos de Lora", "estado": "Mérida", "capital": "Santa Elena de Arenales", "latitud": 8.8, "longitud": -71.4 },
  { "municipio": "Padre Noguera", "estado": "Mérida", "capital": "Santa María de Caparo", "latitud": 8, "longitud": -71.5 },
  { "municipio": "Pueblo Llano", "estado": "Mérida", "capital": "Pueblo Llano", "latitud": 8.9, "longitud": -70.8 },
  { "municipio": "Rangel", "estado": "Mérida", "capital": "Mucuchíes", "latitud": 8.7, "longitud": -70.9 },
  { "municipio": "Rivas Dávila", "estado": "Mérida", "capital": "Bailadores", "latitud": 8.2, "longitud": -71.8 },
  { "municipio": "Santos Marquina", "estado": "Mérida", "capital": "Tabay", "latitud": 8.6, "longitud": -71 },
  { "municipio": "Sucre", "estado": "Mérida", "capital": "Lagunillas", "latitud": 8.5, "longitud": -71.3833 },
  { "municipio": "Tovar", "estado": "Mérida", "capital": "Tovar", "latitud": 8.33333, "longitud": -71.75 },
  { "municipio": "Tulio Febres Cordero", "estado": "Mérida", "capital": "Nueva Bolivia", "latitud": 9, "longitud": -71.3 },
  { "municipio": "Zea", "estado": "Mérida", "capital": "Zea", "latitud": 8.4, "longitud": -71.8 },
  { "municipio": "Acevedo", "estado": "Miranda", "capital": "Caucagua", "latitud": 10.3, "longitud": -66.4 },
  { "municipio": "Andrés Bello", "estado": "Miranda", "capital": "San José de Barlovento", "latitud": 10.2, "longitud": -66.1 },
  { "municipio": "Baruta", "estado": "Miranda", "capital": "Baruta", "latitud": 10.434, "longitud": -66.8766 },
  { "municipio": "Brión", "estado": "Miranda", "capital": "Higuerote", "latitud": 10.5, "longitud": -66.1 },
  { "municipio": "Buroz", "estado": "Miranda", "capital": "Mamporal", "latitud": 10.3, "longitud": -66.2 },
  { "municipio": "Carrizal", "estado": "Miranda", "capital": "Carrizal", "latitud": 10.3, "longitud": -66.9 },
  { "municipio": "Chacao", "estado": "Miranda", "capital": "Chacao", "latitud": 10.5, "longitud": -66.8 },
  { "municipio": "Cristóbal Rojas", "estado": "Miranda", "capital": "Charallave", "latitud": 10.2, "longitud": -66.8 },
  { "municipio": "El Hatillo", "estado": "Miranda", "capital": "El Hatillo", "latitud": 10.4299, "longitud": -66.8166 },
  { "municipio": "Guaicaipuro", "estado": "Miranda", "capital": "Los Teques", "latitud": 10.3, "longitud": -67 },
  { "municipio": "Independencia", "estado": "Miranda", "capital": "Santa Teresa del Tuy", "latitud": 10.2, "longitud": -66.6 },
  { "municipio": "Lander", "estado": "Miranda", "capital": "Ocumare del Tuy", "latitud": 10.1, "longitud": -66.7 },
  { "municipio": "Los Salias", "estado": "Miranda", "capital": "San Antonio de los Altos", "latitud": 10.4, "longitud": -66.9 },
  { "municipio": "Páez", "estado": "Miranda", "capital": "Río Chico", "latitud": 10.3, "longitud": -65.9 },
  { "municipio": "Paz Castillo", "estado": "Miranda", "capital": "Santa Lucía", "latitud": 10.3, "longitud": -66.6 },
  { "municipio": "Pedro Gual", "estado": "Miranda", "capital": "Cúpira", "latitud": 10.1, "longitud": -65.7 },
  { "municipio": "Plaza", "estado": "Miranda", "capital": "Guarenas", "latitud": 10.4, "longitud": -66.6 },
  { "municipio": "Simón Bolívar", "estado": "Miranda", "capital": "San Francisco de Yare", "latitud": 10.2, "longitud": -66.7 },
  { "municipio": "Sucre", "estado": "Miranda", "capital": "Petare", "latitud": 10.4833, "longitud": -66.8167 },
  { "municipio": "Urdaneta", "estado": "Miranda", "capital": "Cúa", "latitud": 10.1, "longitud": -66.8 },
  { "municipio": "Zamora", "estado": "Miranda", "capital": "Guatire", "latitud": 10.4, "longitud": -66.5 },
  { "municipio": "Acosta", "estado": "Monagas", "capital": "San Antonio de Capayacuar", "latitud": 10.2, "longitud": -63.5 },
  { "municipio": "Aguasay", "estado": "Monagas", "capital": "Aguasay", "latitud": 9.41667, "longitud": -63.7333 },
  { "municipio": "Bolívar", "estado": "Monagas", "capital": "Caripito", "latitud": 10.1167, "longitud": -63.1167 },
  { "municipio": "Caripe", "estado": "Monagas", "capital": "Caripe", "latitud": 10.2, "longitud": -63.5 },
  { "municipio": "Cedeño", "estado": "Monagas", "capital": "Caicara de Maturín", "latitud": 9.8, "longitud": -63.6 },
  { "municipio": "Ezequiel Zamora", "estado": "Monagas", "capital": "Punta de Mata", "latitud": 9.68333, "longitud": -63.6167 },
  { "municipio": "Libertador", "estado": "Monagas", "capital": "Temblador", "latitud": 8.98333, "longitud": -62.6333 },
  { "municipio": "Maturín", "estado": "Monagas", "capital": "Maturín", "latitud": 9.74694, "longitud": -63.1764 },
  { "municipio": "Piar", "estado": "Monagas", "capital": "Aragua de Maturín", "latitud": 9.9, "longitud": -63.5 },
  { "municipio": "Punceres", "estado": "Monagas", "capital": "Quiriquire", "latitud": 9.8, "longitud": -63.3 },
  { "municipio": "Santa Bárbara", "estado": "Monagas", "capital": "Santa Bárbara", "latitud": 9.6, "longitud": -63.6 },
  { "municipio": "Sotillo", "estado": "Monagas", "capital": "Barrancas del Orinoco", "latitud": 8.7, "longitud": -62.2 },
  { "municipio": "Uracoa", "estado": "Monagas", "capital": "Uracoa", "latitud": 8.9, "longitud": -62.4 },
  { "municipio": "Antolín del Campo", "estado": "Nueva Esparta", "capital": "La Plaza de Paraguachí", "latitud": 11, "longitud": -63.8 },
  { "municipio": "Arismendi", "estado": "Nueva Esparta", "capital": "La Asunción", "latitud": 11.0333, "longitud": -63.8667 },
  { "municipio": "Díaz", "estado": "Nueva Esparta", "capital": "San Juan Bautista", "latitud": 11, "longitud": -63.9 },
  { "municipio": "García", "estado": "Nueva Esparta", "capital": "El Valle del Espíritu Santo", "latitud": 11, "longitud": -63.8 },
  { "municipio": "Gómez", "estado": "Nueva Esparta", "capital": "Santa Ana", "latitud": 11.1167, "longitud": -63.9167 },
  { "municipio": "Maneiro", "estado": "Nueva Esparta", "capital": "Pampatar", "latitud": 11, "longitud": -63.8 },
  { "municipio": "Marcano", "estado": "Nueva Esparta", "capital": "Juan Griego", "latitud": 11.0833, "longitud": -63.9667 },
  { "municipio": "Mariño", "estado": "Nueva Esparta", "capital": "Porlamar", "latitud": 10.95, "longitud": -63.85 },
  { "municipio": "Península de Macanao", "estado": "Nueva Esparta", "capital": "Boca de Río", "latitud": 10.9, "longitud": -64.2 },
  { "municipio": "Tubores", "estado": "Nueva Esparta", "capital": "Punta de Piedras", "latitud": 10.9, "longitud": -64 },
  { "municipio": "Villalba", "estado": "Nueva Esparta", "capital": "San Pedro de Coche", "latitud": 10.8, "longitud": -63.9 },
  { "municipio": "Agua Blanca", "estado": "Portuguesa", "capital": "Agua Blanca", "latitud": 9.5, "longitud": -69 },
  { "municipio": "Araure", "estado": "Portuguesa", "capital": "Araure", "latitud": 9.56667, "longitud": -69.2167 },
  { "municipio": "Esteller", "estado": "Portuguesa", "capital": "Píritu", "latitud": 9.4, "longitud": -69.3 },
  { "municipio": "Guanare", "estado": "Portuguesa", "capital": "Guanare", "latitud": 9.05, "longitud": -69.75 },
  { "municipio": "Guanarito", "estado": "Portuguesa", "capital": "Guanarito", "latitud": 8.7, "longitud": -69.2 },
  { "municipio": "Monseñor José Vicente de Unda", "estado": "Portuguesa", "capital": "Paraíso de Chabasquén", "latitud": 9.5, "longitud": -70 },
  { "municipio": "Ospino", "estado": "Portuguesa", "capital": "Ospino", "latitud": 9.3, "longitud": -69.45 },
  { "municipio": "Páez", "estado": "Portuguesa", "capital": "Acarigua", "latitud": 9.55, "longitud": -69.2 },
  { "municipio": "Papelón", "estado": "Portuguesa", "capital": "Papelón", "latitud": 8.9, "longitud": -69.3 },
  { "municipio": "San Genaro de Boconoíto", "estado": "Portuguesa", "capital": "Boconoíto", "latitud": 9, "longitud": -69.9 },
  { "municipio": "San Rafael de Onoto", "estado": "Portuguesa", "capital": "San Rafael de Onoto", "latitud": 9.6, "longitud": -69 },
  { "municipio": "Santa Rosalía", "estado": "Portuguesa", "capital": "El Playón", "latitud": 9.2, "longitud": -69.1 },
  { "municipio": "Sucre", "estado": "Portuguesa", "capital": "Biscucuy", "latitud": 9.3, "longitud": -70 },
  { "municipio": "Turén", "estado": "Portuguesa", "capital": "Villa Bruzual", "latitud": 9.33333, "longitud": -69.1167 },
  { "municipio": "Andrés Eloy Blanco", "estado": "Sucre", "capital": "Casanay", "latitud": 10.4, "longitud": -63.4 },
  { "municipio": "Benítez", "estado": "Sucre", "capital": "El Pilar", "latitud": 10.5, "longitud": -63.1 },
  { "municipio": "Bermúdez", "estado": "Sucre", "capital": "Carúpano", "latitud": 10.6667, "longitud": -63.25 },
  { "municipio": "Bolívar", "estado": "Sucre", "capital": "Marigüitar", "latitud": 10.3, "longitud": -64 },
  { "municipio": "Cajigal", "estado": "Sucre", "capital": "Yaguaraparo", "latitud": 10.6, "longitud": -62.8 },
  { "municipio": "Cruz Salmerón Acosta", "estado": "Sucre", "capital": "Araya", "latitud": 10.5667, "longitud": -64.25 },
  { "municipio": "Libertador", "estado": "Sucre", "capital": "Tunapuy", "latitud": 10.5, "longitud": -63 },
  { "municipio": "Mariño", "estado": "Sucre", "capital": "Irapa", "latitud": 10.6, "longitud": -62.6 },
  { "municipio": "Mejía", "estado": "Sucre", "capital": "San Antonio del Golfo", "latitud": 10.4, "longitud": -63.9 },
  { "municipio": "Montes", "estado": "Sucre", "capital": "Cumanacoa", "latitud": 10.2, "longitud": -63.9 },
  { "municipio": "Ribero", "estado": "Sucre", "capital": "Cariaco", "latitud": 10.5, "longitud": -63.55 },
  { "municipio": "Sucre", "estado": "Sucre", "capital": "Cumaná", "latitud": 10.45, "longitud": -64.1667 },
  { "municipio": "Valdez", "estado": "Sucre", "capital": "Güiria", "latitud": 10.5667, "longitud": -62.3 },
  { "municipio": "Andrés Bello", "estado": "Táchira", "capital": "Cordero", "latitud": 7.9, "longitud": -72.2 },
  { "municipio": "Antonio Rómulo Costa", "estado": "Táchira", "capital": "Las Mesas", "latitud": 8.1, "longitud": -72.1 },
  { "municipio": "Ayacucho", "estado": "Táchira", "capital": "Colón", "latitud": 8.03333, "longitud": -72.25 },
  { "municipio": "Bolívar", "estado": "Táchira", "capital": "San Antonio del Táchira", "latitud": 7.81667, "longitud": -72.45 },
  { "municipio": "Cárdenas", "estado": "Táchira", "capital": "Táriba", "latitud": 7.8, "longitud": -72.2 },
  { "municipio": "Córdoba", "estado": "Táchira", "capital": "Santa Ana del Táchira", "latitud": 7.6, "longitud": -72.2 },
  { "municipio": "Fernández Feo", "estado": "Táchira", "capital": "San Rafael del Piñal", "latitud": 7.5, "longitud": -71.9 },
  { "municipio": "Francisco de Miranda", "estado": "Táchira", "capital": "San José de Bolívar", "latitud": 8, "longitud": -71.9 },
  { "municipio": "García de Hevia", "estado": "Táchira", "capital": "La Fría", "latitud": 8.21667, "longitud": -72.25 },
  { "municipio": "Guásimos", "estado": "Táchira", "capital": "Palmira", "latitud": 7.8, "longitud": -72.2 },
  { "municipio": "Independencia", "estado": "Táchira", "capital": "Capacho Nuevo", "latitud": 7.8, "longitud": -72.3 },
  { "municipio": "Jáuregui", "estado": "Táchira", "capital": "La Grita", "latitud": 8.1, "longitud": -72 },
  { "municipio": "José María Vargas", "estado": "Táchira", "capital": "El Cobre", "latitud": 8, "longitud": -72 },
  { "municipio": "Junín", "estado": "Táchira", "capital": "Rubio", "latitud": 7.7, "longitud": -72.35 },
  { "municipio": "Libertad", "estado": "Táchira", "capital": "Capacho Viejo", "latitud": 7.8, "longitud": -72.3 },
  { "municipio": "Libertador", "estado": "Táchira", "capital": "Abejales", "latitud": 7.6, "longitud": -71.6 },
  { "municipio": "Lobatera", "estado": "Táchira", "capital": "Lobatera", "latitud": 7.9, "longitud": -72.3 },
  { "municipio": "Michelena", "estado": "Táchira", "capital": "Michelena", "latitud": 7.9, "longitud": -72.2 },
  { "municipio": "Panamericano", "estado": "Táchira", "capital": "Coloncito", "latitud": 8.1, "longitud": -72.1 },
  { "municipio": "Pedro María Ureña", "estado": "Táchira", "capital": "Ureña", "latitud": 7.9, "longitud": -72.4 },
  { "municipio": "Rafael Urdaneta", "estado": "Táchira", "capital": "Delicias", "latitud": 7.6, "longitud": -72.4 },
  { "municipio": "Samuel Darío Maldonado", "estado": "Táchira", "capital": "La Tendida", "latitud": 8.3, "longitud": -72.1 },
  { "municipio": "San Cristóbal", "estado": "Táchira", "capital": "San Cristóbal", "latitud": 7.76694, "longitud": -72.2253 },
  { "municipio": "Seboruco", "estado": "Táchira", "capital": "Seboruco", "latitud": 8.1, "longitud": -72 },
  { "municipio": "Simón Rodríguez", "estado": "Táchira", "capital": "San Simón", "latitud": 7.5, "longitud": -72.1 },
  { "municipio": "Sucre", "estado": "Táchira", "capital": "Queniquea", "latitud": 7.9, "longitud": -71.9 },
  { "municipio": "Torbes", "estado": "Táchira", "capital": "San Josecito", "latitud": 7.7, "longitud": -72.2 },
  { "municipio": "Uribante", "estado": "Táchira", "capital": "Pregonero", "latitud": 7.9, "longitud": -71.8 },
  { "municipio": "Andrés Bello", "estado": "Trujillo", "capital": "Santa Isabel", "latitud": 9.8, "longitud": -70.6 },
  { "municipio": "Boconó", "estado": "Trujillo", "capital": "Boconó", "latitud": 9.25, "longitud": -70.25 },
  { "municipio": "Bolívar", "estado": "Trujillo", "capital": "Sabana Grande", "latitud": 9.5, "longitud": -70.5 },
  { "municipio": "Candelaria", "estado": "Trujillo", "capital": "Chejendé", "latitud": 9.6, "longitud": -70.4 },
  { "municipio": "Carache", "estado": "Trujillo", "capital": "Carache", "latitud": 9.65, "longitud": -70.2333 },
  { "municipio": "Escuque", "estado": "Trujillo", "capital": "Escuque", "latitud": 9.3, "longitud": -70.7 },
  { "municipio": "José Felipe Márquez Cañizales", "estado": "Trujillo", "capital": "El Paradero", "latitud": 9.7, "longitud": -70.5 },
  { "municipio": "Juan Vicente Campo Elías", "estado": "Trujillo", "capital": "Campo Elías", "latitud": 9.4, "longitud": -70.3 },
  { "municipio": "La Ceiba", "estado": "Trujillo", "capital": "Santa Apolonia", "latitud": 9.6, "longitud": -71 },
  { "municipio": "Miranda", "estado": "Trujillo", "capital": "El Dividive", "latitud": 9.6, "longitud": -70.7 },
  { "municipio": "Monte Carmelo", "estado": "Trujillo", "capital": "Monte Carmelo", "latitud": 9.4, "longitud": -70.5 },
  { "municipio": "Motatán", "estado": "Trujillo", "capital": "Motatán", "latitud": 9.4, "longitud": -70.6 },
  { "municipio": "Pampán", "estado": "Trujillo", "capital": "Pampán", "latitud": 9.4, "longitud": -70.5 },
  { "municipio": "Pampanito", "estado": "Trujillo", "capital": "Pampanito", "latitud": 9.4, "longitud": -70.5 },
  { "municipio": "Rafael Rangel", "estado": "Trujillo", "capital": "Betijoque", "latitud": 9.3, "longitud": -70.8 },
  { "municipio": "San Rafael de Carvajal", "estado": "Trujillo", "capital": "Carvajal", "latitud": 9.3, "longitud": -70.6 },
  { "municipio": "Sucre", "estado": "Trujillo", "capital": "Sabana de Mendoza", "latitud": 9.5, "longitud": -70.8 },
  { "municipio": "Trujillo", "estado": "Trujillo", "capital": "Trujillo", "latitud": 9.36667, "longitud": -70.4333 },
  { "municipio": "Urdaneta", "estado": "Trujillo", "capital": "La Quebrada", "latitud": 9.16667, "longitud": -70.5833 },
  { "municipio": "Valera", "estado": "Trujillo", "capital": "Valera", "latitud": 9.31667, "longitud": -70.6 },
  { "municipio": "Vargas", "estado": "Vargas", "capital": "La Guaira", "latitud": 10.6, "longitud": -66.9333 },
  { "municipio": "Arístides Bastidas", "estado": "Yaracuy", "capital": "San Pablo", "latitud": 10.3, "longitud": -68.8 },
  { "municipio": "Bolívar", "estado": "Yaracuy", "capital": "Aroa", "latitud": 10.4, "longitud": -68.9 },
  { "municipio": "Bruzual", "estado": "Yaracuy", "capital": "Chivacoa", "latitud": 10.1667, "longitud": -68.9 },
  { "municipio": "Cocorote", "estado": "Yaracuy", "capital": "Cocorote", "latitud": 10.3167, "longitud": -68.7833 },
  { "municipio": "Independencia", "estado": "Yaracuy", "capital": "Independencia", "latitud": 10.3, "longitud": -68.7 },
  { "municipio": "José Antonio Páez", "estado": "Yaracuy", "capital": "Sabana de Parra", "latitud": 10.1, "longitud": -69.1 },
  { "municipio": "La Trinidad", "estado": "Yaracuy", "capital": "Boraure", "latitud": 10.2, "longitud": -68.8 },
  { "municipio": "Manuel Monge", "estado": "Yaracuy", "capital": "Yumare", "latitud": 10.5, "longitud": -68.7 },
  { "municipio": "Nirgua", "estado": "Yaracuy", "capital": "Nirgua", "latitud": 10.15, "longitud": -68.5667 },
  { "municipio": "Peña", "estado": "Yaracuy", "capital": "Yaritagua", "latitud": 10.0833, "longitud": -69.1333 },
  { "municipio": "San Felipe", "estado": "Yaracuy", "capital": "San Felipe", "latitud": 10.3333, "longitud": -68.7333 },
  { "municipio": "Sucre", "estado": "Yaracuy", "capital": "Guama", "latitud": 10.3, "longitud": -68.8 },
  { "municipio": "Urachiche", "estado": "Yaracuy", "capital": "Urachiche", "latitud": 10.2, "longitud": -69 },
  { "municipio": "Veroes", "estado": "Yaracuy", "capital": "Farriar", "latitud": 10.4, "longitud": -68.6 },
  { "municipio": "Almirante Padilla", "estado": "Zulia", "capital": "El Toro", "latitud": 10.9, "longitud": -71.6 },
  { "municipio": "Baralt", "estado": "Zulia", "capital": "San Timoteo", "latitud": 9.8, "longitud": -71 },
  { "municipio": "Cabimas", "estado": "Zulia", "capital": "Cabimas", "latitud": 10.3978, "longitud": -71.4464 },
  { "municipio": "Catatumbo", "estado": "Zulia", "capital": "Encontrados", "latitud": 9.2, "longitud": -72.3 },
  { "municipio": "Colón", "estado": "Zulia", "capital": "San Carlos del Zulia", "latitud": 9, "longitud": -71.9 },
  { "municipio": "Francisco Javier Pulgar", "estado": "Zulia", "capital": "Pueblo Nuevo-El Chivo", "latitud": 8.9, "longitud": -71.9 },
  { "municipio": "Guajira", "estado": "Zulia", "capital": "Sinamaica", "latitud": 11.1, "longitud": -71.9 },
  { "municipio": "Jesús Enrique Losada", "estado": "Zulia", "capital": "La Concepción", "latitud": 10.6, "longitud": -71.9 },
  { "municipio": "Jesús María Semprún", "estado": "Zulia", "capital": "Casigua El Cubo", "latitud": 9, "longitud": -72.6 },
  { "municipio": "La Cañada de Urdaneta", "estado": "Zulia", "capital": "Concepción", "latitud": 10.4, "longitud": -71.7 },
  { "municipio": "Lagunillas", "estado": "Zulia", "capital": "Ciudad Ojeda", "latitud": 10.2, "longitud": -71.3 },
  { "municipio": "Machiques de Perijá", "estado": "Zulia", "capital": "Machiques", "latitud": 10.0667, "longitud": -72.5667 },
  { "municipio": "Mara", "estado": "Zulia", "capital": "San Rafael del Moján", "latitud": 10.8, "longitud": -71.7 },
  { "municipio": "Maracaibo", "estado": "Zulia", "capital": "Maracaibo", "latitud": 10.6316, "longitud": -71.6444 },
  { "municipio": "Miranda", "estado": "Zulia", "capital": "Los Puertos de Altagracia", "latitud": 10.7, "longitud": -71.5 },
  { "municipio": "Rosario de Perijá", "estado": "Zulia", "capital": "La Villa del Rosario", "latitud": 10.3, "longitud": -72.3 },
  { "municipio": "San Francisco", "estado": "Zulia", "capital": "San Francisco", "latitud": 10.5, "longitud": -71.6 },
  { "municipio": "Santa Rita", "estado": "Zulia", "capital": "Santa Rita", "latitud": 10.5, "longitud": -71.5 },
  { "municipio": "Simón Bolívar", "estado": "Zulia", "capital": "Tía Juana", "latitud": 10.2, "longitud": -71.4 },
  { "municipio": "Sucre", "estado": "Zulia", "capital": "Bobures", "latitud": 9.3, "longitud": -71.1 },
  { "municipio": "Valmore Rodríguez", "estado": "Zulia", "capital": "Bachaquero", "latitud": 9.9, "longitud": -71.1 }
];